### ISSUE TITLE
Create prototype

### ISSUE THREAD

**Issue by webmozart** [webmozart/php-scoper#1]
The first task here is to create a prototype of the "add-prefix" command. The stub of this command and its test is already there. The implementation should look for all

* namespace declarations
* use statements
* fully qualified usages of class/interface/trait names

in a directory/file and add the passed prefix. Read the [README](https://github.com/webmozart/php-scoper/blob/master/README.md) to learn more. Probably we can use https://github.com/nikic/PHP-Parser to do the parsing, although I don't know whether it's possible to access the position of the parsed token in the file from the parser to do the actual string replacement (cc @nikic).

This should be fun :) This is available for grabs if anyone wants to give it a try.

**Comment by sebastianbergmann** [comment]
Alternatively, [nikic/php-ast](https://github.com/nikic/php-ast) could be used as the backend instead of [nikic/PHP-Parser](https://github.com/nikic/PHP-Parser). That would require PHP 7 to work but would be future-proof.

**Comment by nikic** [comment]
Accessing the file position is possible, see https://github.com/nikic/PHP-Parser/blob/master/doc/component/Lexer.markdown#lexer-options. Assuming version 2 of the library, you need to create the parser using

```php
$parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7, new Lexer([
    'usedAttributes' => [
         'docComment', 'startLine', 'endLine', 'startFilePos', 'endFilePos'
    ],
]));
```

and then access the position using `$node->getAttribute('startFilePos')` etc.

I combine this with a class that queues up modifications based on original offsets and then applies them all at once. (Doing it on the fly is a PITA because you need to track offset changes through the file).

**Comment by webmozart** [comment]
@sebastianbergmann Can those tools be used for PHP 5 source code?

**Comment by webmozart** [comment]
@nikic Perfect, thanks!

**Comment by sebastianbergmann** [comment]
@webmozart Sure.

**Comment by matthieuauger** [comment]
Hi,

@webmozart I'd love to give it try, currently working on a first implementation. Can we agree to use the version 2 of nikic/PHP-Parser, even if it's still in alpha ?

Thanks

**Comment by webmozart** [comment]
@matthieuauger sure, whatever you think is best :)
